apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      annotations:
        ad.datadoghq.com/nodejs.logs: '[{"source":"nodejs","service":"nodejs"}]'
      labels:
        app: nodejs
    spec:
      containers:
        - name: app
          image: gcr.io/trial-demo-dev/trial-demo-dev:v1.5.7
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer