---
apiVersion: v1
kind: Service
metadata:
  name: version1-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: app


apiVersion: apps/v1
kind: Deployment
metadata:
  name: version2-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: dedyyyy/trial-demo-dev:2.0.0
        ports:
        - containerPort: 3000