apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      annotations:
        ad.datadoghq.com/app.logs: '[{"source":"app","service":"nodejs-service"}]'
      labels:
        app: nodejs
    spec:
      containers:
        - name: app
          image: gcr.io/trial-demo-dev/trial-demo-dev:v1.5.7
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
