version: 2.1
orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2
  docker: circleci/docker@1.0.0
  gcp-gcr: circleci/gcp-gcr@0.6.1


jobs:
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          deployment: nodejs-cluster
          container: dominic-backend
          image: gcr.io/trial-demo-dev/trial-demo-dev:v3 # change version when updating
workflows:
  build_and_build_images:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: myContext
          image: trial-demo-dev    
      - deploy