version: 2.1
orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@1.0.3
  gcr: circleci/gcp-gcr@0.0.2
  docker: circleci/docker@1.0.0
  gcp-gcr: circleci/gcp-gcr@0.6.1


jobs:
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          cluster: nodeje-cluster
          deployment: app-deployment
          container: app
          image: gcr.io/trial-demo-dev/trial-demo-dev
          tag: v3 # change version when updating
workflows:
  build_and_build_images:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: trial-demo-dev
          tag: v3
      - deploy:
          requires: 
            - gcp-gcr/build-and-push-image