version: 2.1
orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2
  docker: circleci/docker@1.0.0
  gcp-gcr: circleci/gcp-gcr@0.6.1


jobs:
  build-and-push-image:
    description: |
      Install GCP CLI, if needed, and configure. Build and push image to repository.
    executor: default
    parameters:
      dockerfile:
        default: Dockerfile
        description: 'Name of dockerfile to use, defaults to Dockerfile'
        type: string
      gcloud-service-key:
        default: GCLOUD_SERVICE_KEY
        description: The gcloud service key
        type: env_var_name
      google-compute-zone:
        default: GOOGLE_COMPUTE_ZONE
        description: The Google compute zone to connect with via the gcloud CLI
        type: env_var_name
      google-project-id:
        default: GOOGLE_PROJECT_ID
        description: The Google project ID to connect with via the gcloud CLI
        type: env_var_name
      image:
        default: trial-demo-dev
        description: A name for your Docker image
        type: string
      path:
        default: .
        description: >
          Path to the directory containing your Dockerfile and build context,
          defaults to . (working directory)
        type: string
      registry-url:
        default: gcr.io
        description: 'The GCR registry URL from ['''', us, eu, asia].gcr.io'
        type: string
      tag:
        default: v3
        description: A Docker image tag
        type: string
    steps:
      - checkout
      - gcr-auth:
          gcloud-service-key: <<parameters.gcloud-service-key>>
          google-compute-zone: <<parameters.google-compute-zone>>
          google-project-id: <<parameters.google-project-id>>
      - build-image:
          dockerfile: <<parameters.dockerfile>>
          google-project-id: <<parameters.google-project-id>>
          image: <<parameters.image>>
          path: <<parameters.path>>
          registry-url: <<parameters.registry-url>>
          tag: <<parameters.tag>>
      - push-image:
          google-project-id: <<parameters.google-project-id>>
          image: <<parameters.image>>
          registry-url: <<parameters.registry-url>>
          tag: <<parameters.tag>>
   
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          deployment: nodejs-cluster
          container: dominic-backend
          image: gcr.io/trial-demo-dev/trial-demo-dev:v3 # change version when updating
workflows:
  build_update_deploy:
    jobs:
      - build-and-push-image
      - deploy