apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-app-pod-sidecar-log-agent-config-map
data:
  config.toml: |
    default_api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2FwaS50aW1iZXIuaW8vIiwiZXhwIjpudWxsLCJpYXQiOjE1ODQwNzQyMjYsImlzcyI6Imh0dHBzOi8vYXBpLnRpbWJlci5pby9hcGlfa2V5cyIsInByb3ZpZGVyX2NsYWltcyI6eyJhcGlfa2V5X2lkIjo2ODk0LCJ1c2VyX2lkIjoiYXBpX2tleXw2ODk0In0sInN1YiI6ImFwaV9rZXl8Njg5NCJ9.8MatG0Tk6XQPRv3JcUHT0-m4ibg2l7WF0SvfaqXyga0"
    [[files]]
    path = "/var/log/logging-app/app.log"
---
apiVersion: v1
kind: Pod
metadata:
  name: logging-app-pod-sidecar-log-agent
spec:
  containers:
  - name: logging-app
    image: timberio/logging-app
    args: ["-file", "/var/log/logging-app/app.log"]
    volumeMounts:
    - name: logging-app-log-dir
      mountPath: /var/log/logging-app
  - name: timber-agent
    image: "timberio/agent:0.8.1"
    args: ["capture-files", "-c", "/timber/config.toml"]
    volumeMounts:
    - name: logging-app-pod-sidecar-log-agent-config-map
      mountPath: /timber
      readOnly: true
    - name: logging-app-log-dir
      mountPath: /var/log/logging-app
  volumes:
  - name: logging-app-log-dir
    emptyDir: {}
  - name: logging-app-pod-sidecar-log-agent-config-map
    configMap:
      name: logging-app-pod-sidecar-log-agent-config-map